### ISSUE TITLE
Reference needed

### ISSUE THREAD

**Issue by Offirmo** [vladocar/CSS-Micro-Reset#5]
Hey!

This micro-reset looks very short. Is that because all other properties are perfectly aligned on all major browsers?

If not, why just those resets? Do you have any references?

**Comment by Offirmo** [comment]
A full blog post would be very interesting.

**Comment by vladocar** [comment]
All the properties will not be perfectly aligned. Just the most common. It is Ok some properties to look different in different browsers. It is also Ok not to have CSS reset. If you want full reset you should probably go with normalize.css
